TeamOnBoarding/TeamOnBoarding/Controllers/AssessmentController.cs
using System.Web.Mvc;
using TeamOnBoarding.DomainModel.Classes;
using TeamOnBoarding.Models;
using TeamOnBoarding.SqlRepository.Repositories;

namespace TeamOnBoarding.Controllers
{
    [Authorize(Roles = "admin")]
    public class AssessmentController : BaseController
    {
        private readonly CourseRepository _courseRepository;
        private readonly CourseModel _courseModel;

        public AssessmentController()
        {
            _courseRepository = new CourseRepository();
            _courseModel = new CourseModel(HomeLayoutModel);
        }

        public ActionResult Index(int courseId)
        {
            var course = _courseRepository.GetById(courseId);
            _courseModel.CourseId = course.Id;
            _courseModel.CourseName = course.CourseName;
            return View(_courseModel);
        }

        public JsonResult GetQuestions(int courseId)
        {
            var questions = _courseRepository.GetQuestionsByCourse(courseId);
            return new JsonResult() { Data = questions, MaxJsonLength = int.MaxValue, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult SaveQuestion(QuestionModel questionmodel)
        {
            var result = _courseRepository.AddQuestion(questionmodel);
            return new JsonResult() { Data = result, MaxJsonLength = int.MaxValue, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult UpdateQuestion(QuestionModel questionmodel)
        {
            var result = _courseRepository.UpdateQuestion(questionmodel);
            return new JsonResult() { Data = result, MaxJsonLength = int.MaxValue, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult DeleteQuestion(int questionId)
        {
            var result = _courseRepository.DeleteQuestion(questionId);
            return new JsonResult() { Data = result, MaxJsonLength = int.MaxValue, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

TeamOnBoarding/TeamOnBoarding/Controllers/UserAssessmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using TeamOnBoarding.DomainModel.DTO;
using TeamOnBoarding.Library.Common;
using TeamOnBoarding.Library.Common.Enum;
using TeamOnBoarding.Models;
using TeamOnBoarding.SqlRepository.Repositories;

namespace TeamOnBoarding.Controllers
{
	[Authorize(Roles="user")]
	public class UserAssessmentController : BaseController
	{
		private readonly CourseRepository _courseRepository;
		private readonly UserAssessmentRepository _userAssessmentRepository;
		private readonly UserAssessmentModel _userAssessmentModel;

		public UserAssessmentController()
		{
			_courseRepository = new CourseRepository();
			_userAssessmentRepository = new UserAssessmentRepository();
			_userAssessmentModel = new UserAssessmentModel(HomeLayoutModel);
		}

		public ActionResult Index(int courseId)
		{
			var userAssessmentStatus = _userAssessmentRepository.GetUserAssessmentStatus(_userAssessmentModel.UserId, courseId);
			var course = _courseRepository.GetById(courseId);
			_userAssessmentModel.CourseId = course.Id;
			_userAssessmentModel.CourseName = course.CourseName;
			_userAssessmentModel.UserAssessmentStatus = UserAssessmentStatusType.NotStarted.ToString();
			if (userAssessmentStatus != null)
			{
				_userAssessmentModel.UserAssessmentStatus = userAssessmentStatus.Status;
				return View(_userAssessmentModel);
			}
			var questions = _courseRepository.GetQuestionsByCourse(courseId);
			var totalTime = DataConversion.ConvertSecondsToMinute(questions.Select(x => x.QuestionTime).Sum());
			_userAssessmentModel.TotalTime = totalTime;
			_userAssessmentModel.QuestionCount = questions.Count;
			return View(_userAssessmentModel);
		}

		public JsonResult GetQuestions(int courseId)
		{
			var questions = _courseRepository.GetQuestionsByCourse(courseId);
			return new JsonResult() { Data = questions, MaxJsonLength = Int32.MaxValue, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
		}

		public JsonResult SetUserAssessmentStatus(int courseId)
		{
			var response = _userAssessmentRepository.AddUserAssessmentStatus(courseId, _userAssessmentModel.UserId, UserAssessmentStatusType.Started);
			return new JsonResult() { Data = response, MaxJsonLength = Int32.MaxValue, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
		}

		public JsonResult SubmitTest(List<QuestionResponseModel> questionResponse, int courseId)
		{
			Mapper.CreateMap<QuestionResponseModel, QuestionResponseDto>();
			var questionResponseDto = Mapper.Map<List<QuestionResponseModel>, List<QuestionResponseDto>>(questionResponse);
			var submitStatus = _userAssessmentRepository.SubmitTest(questionResponseDto, _userAssessmentModel.UserId, courseId);
			return new JsonResult() { Data = submitStatus, MaxJsonLength = Int32.MaxValue, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
		}
	}
}

TeamOnBoarding/TeamOnBoarding/Controllers/UserCourseController.cs
using System.Web.Mvc;
using TeamOnBoarding.Models;
using TeamOnBoarding.SqlRepository.Repositories;

namespace TeamOnBoarding.Controllers
{
	[Authorize(Roles = "user")]
	public class UserCourseController : BaseController
	{
	    private readonly CourseRepository _courseRepository;

		public UserCourseController()
		{
			_courseRepository = new CourseRepository();
		}

		public ActionResult Index(int courseId)
		{
			var content = _courseRepository.GetCourseContent(courseId);
			var course = _courseRepository.GetById(courseId);
			var userCourseModel = new UserCourseModel(HomeLayoutModel) { CourseId = courseId, CourseContent = content, CourseName = course.CourseName };
			return View(userCourseModel);
		}
	}
}

TeamOnBoarding/TeamOnBoarding/Views/Shared/_Layout.cshtml
@model TeamOnBoarding.Models.HomeLayoutModel
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title - My ASP.NET MVC Application</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<link rel="stylesheet" type="text/css" href="~/Content/nanoScroller/nanoscroller.css" />
	<link rel="stylesheet" type="text/css" href="~/Content/font-awesome/css/font-awesome.min.css" />
	<link rel="stylesheet" type="text/css" href="~/Content/material-design-icons/css/material-design-icons.min.css" />
	<link rel="stylesheet" type="text/css" href="~/Content/site.css" />
	<link rel="stylesheet" type="text/css" href="~/Content/style.css" />
	<link rel="stylesheet" type="text/css" href="~/Content/ng-grid.min.css" />
	<link rel="stylesheet" type="text/css" href="~/Content/bootstrap/css/bootstrap.min.css" />
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=News+Cycle:400,700' rel='stylesheet' type='text/css'>
	<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
	@Styles.Render("~/Content/css")
	<script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
	<script type="text/javascript" src="~/Scripts/angular/angular.min.js"></script>
	<script type="text/javascript" src="~/Scripts/angular/angular-route.min.js"></script>
	<script type="text/javascript" src="~/Scripts/angular/angular-messages.min.js"></script>
	<script type="text/javascript" src="~/Scripts/angular/ng-grid.min.js"></script>
	<script type="text/javascript" src="~/Scripts/angular/angular-sanitize.min.js"></script>
	<script type="text/javascript" src="~/Scripts/jquery.requestAnimationFrame.min.js"></script>
	<script type="text/javascript" src="~/Scripts/jquery.nanoscroller.min.js"></script>
	<script type="text/javascript" src="~/Scripts/materialize.min.js"></script>
	<script type="text/javascript" src="~/Scripts/Sortable.min.js"></script>
	<script type="text/javascript" src="~/Scripts/bootstrap/bootstrap.min.js"></script>	
	<script type="text/javascript" src="~/Scripts/app/layout-app.js"></script>
	<script type="text/javascript" src="~/Scripts/app/services/baseService.js"></script>
	<script type="text/javascript" src="~/Scripts/app/controllers/menuController.js"></script>
	@Scripts.Render("~/bundles/site")
	@Scripts.Render("~/bundles/modernizr")
	@RenderSection("scripts", required: false)
	@*<base href="http://localhost:50747/"/>*@
</head>
<body data-ng-app="BaseModule">
	<header>
		<nav class="navbar-top navbar-dark">
			<div class="nav-wrapper">
				<!-- Logo -->
				<a href="#!" class="brand-logo">Concourse
				</a>
				<!-- /Logo -->
				<!-- Menu -->
				<ul>
					<li class="user">
						<a class="dropdown-button" href="#!" data-activates="user-dropdown">
							<img src="~/Images/user.jpg" class="circle">@Model.FirstName @Model.LastName<i class="mdi-navigation-expand-more right"></i>
						</a>
					</li>
				</ul>
				<!-- /Menu -->
			</div>
		</nav>
	</header>
	<!--side nav bar starts-->
	<aside class="yaybar yay-shrink yay-gestures">
		<div class="nano-content" data-ng-controller="MenuController as menu">
			<ul class="gw-nav gw-nav-list">
				<li class="label">Navigation</li>
				@if (Model.Role == "admin")
				{
					<li class="init-arrow-down inner1"><a href="javascript:void(0)"><span class="gw-menu-text">Admin</span> <b class="gw-arrow"></b></a>
						<ul class="gw-submenu">
							<li class="inner2" id="User">@Html.ActionLink("User", "Index", "User") </li>
							<li class="inner2" id="Track">@Html.ActionLink("Track", "Index", "Track") </li>
						</ul>
					</li>
				    <li class="init-arrow-down inner1"><a href="javascript:void(0)"><span class="gw-menu-text">Assessment</span> <b class="gw-arrow"></b></a>
				        <ul class="gw-submenu">
				            @foreach (var trackCourse in Model.TrackWithCourseDetails)
				            {
				                <li class="init-arrow-down inner2"><a href="javascript:void(0)"><span class="gw-menu-text">@trackCourse.TrackName</span> <b class="gw-arrow  icon-arrow-up8"></b></a>
				                    <ul>
				                        @foreach (var course in trackCourse.Courses)
				                        {
				                            <li id="AssessmentCourse-@course.CourseId">@Html.ActionLink(course.CourseName, "Index", "Assessment", new {courseId = course.CourseId}, null)</li>
				                        }
				                    </ul>
				                </li>
				            }
				        </ul>
				    </li>
                    <li class="init-arrow-down"><a href="javascript:void(0)"><span class="gw-menu-text">Evaluate User</span> <b class="gw-arrow"></b></a>
						<ul class="gw-submenu">
							@foreach (var user in Model.EvaluationList)
							{
								<li id="AssessmentCourse-@user.UserId">@Html.ActionLink(user.UserName, "Index", "Evaluate", new { user = user.UserId }, null)</li>
							}
						</ul>
					</li>
				}
				@if (Model.Role == "user")
				{
					<li class="init-arrow-down inner1"><a href="javascript:void(0)"><span class="gw-menu-text">My Courses</span> <b class="gw-arrow icon-arrow-up8"></b></a>
						<ul class="gw-submenu inner2">
							@foreach (var trackCourse in Model.TrackWithCourseDetails)
							{
								<li class="init-arrow-down inner2"><a href="javascript:void(0)"><span class="gw-menu-text">@trackCourse.TrackName</span> <b class="gw-arrow  icon-arrow-up8"></b></a>
									<ul>
										@foreach (var course in trackCourse.Courses)
										{
											<li id="UserCourseCourse-@course.CourseId">
												@Html.ActionLink(course.CourseName, "index", "UserCourse", new { courseId = course.CourseId }, null)
												@*<a href="#" data-ng-click="showCourseContent(@course.CourseId, '@course.CourseName')">@course.CourseName</a>*@
											</li>
										}
									</ul>
								</li>
							}
						</ul>
					</li>
					<li class="init-arrow-down inner1"><a href="javascript:void(0)"><span class="gw-menu-text">My Assessment</span> <b class="gw-arrow icon-arrow-up8"></b></a>
						<ul class="gw-submenu inner2">
							@foreach (var trackCourse in Model.TrackWithCourseDetails)
							{
								<li class="init-arrow-down inner2"><a href="javascript:void(0)"><span class="gw-menu-text">@trackCourse.TrackName</span> <b class="gw-arrow  icon-arrow-up8"></b></a>
									<ul>
										@foreach (var course in trackCourse.Courses)
										{
											<li id="UserAssessmentCourse-@course.CourseId">
												@Html.ActionLink(course.CourseName, "index", "UserAssessment", new { courseId = course.CourseId }, null)
												@*<a href="#" data-ng-click="showCourseContent(@course.CourseId, '@course.CourseName')">@course.CourseName</a>*@
											</li>
										}
									</ul>
								</li>
							}
						</ul>
					</li>
				}
			</ul>
		</div>
	</aside>
	<!--side nav bar ends-->

	<section class="content-wrap content-wrapper main-content clear-fix">
		@RenderBody()
	</section>
	<ul id="user-dropdown" class="dropdown-content">
		<li><a href="#"><i class="fa fa-user"></i>Profile</a>
		</li>
		<li class="divider"></li>
		<li><a href="/Login/LogOut"><i class="fa fa-sign-out"></i>Logout</a>
		</li>
	</ul>
	<footer>&copy; 2015 <strong>Team on-boarding</strong>. All rights reserved.</footer>
</body>
</html>

TeamOnBoarding/TeamOnBoarding/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="~/Content/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/site.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/style.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap/css/bootstrap.min.css" />
    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    @Styles.Render("~/Content/css")
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/angular/angular.min.js"></script>
    <script type="text/javascript" src="~/Scripts/angular/angular-route.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/login-angular")
    @Scripts.Render("~/bundles/site")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("scripts", required: false)
</head>
<body data-ng-app="LoginAdministration">
    @RenderBody()
</body>
</html>